spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_hr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: zhang
    password: 050715
    driver-class-name: com.mysql.cj.jdbc.Driver