spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_hr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Zk48658345@1996
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.kezhang.model
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      use-generated-keys: true